### PR TITLE
added select_line_on_copy_empty

### PR DESCRIPTION
**Pull request by ewerybody**
Added option to class CodeEdit to make line selection on copy action +
empty selection optional.

### CODE REVIEW

**Comment by ewerybody** [comment]
Whow! My first ever pull request to another project! :O

**Comment by ewerybody** [comment]
Alright .. can I update the pull request? Or discard it?

**Comment by ewerybody** [comment]
Whow! That looks promising! What do you say?

**Comment by ColinDuquesnoy** [comment]
> Whow! That looks promising! What do you say?

Looks good! Just one question, are there any reason why you haven't implemented this for **cut**?

**Comment by ewerybody** [comment]
Hmmm. So far It didn't bother me for cut.

I see that this could also be useful to have it there but CodeEdit.cut is already a little more complex. At first glance I doubt there is every case covered by the tests for that. I'd say this is a different task.
Or would you even use the same variable to toggle both?

**Comment by ColinDuquesnoy** [comment]
Merged. Thank you very much for your contribution :)

> I see that this could also be useful to have it there but CodeEdit.cut is already a little more complex. At first glance I doubt there is every case covered by the tests for that. I'd say this is a different task.
Or would you even use the same variable to toggle both?

I wrote both the copy/cut together, to me they are quite related, that's why I am asking. But I probably wouldn't use the same property for cut, so I'd say I agree with you this should be a different task. (btw the cut method is [covered](https://coveralls.io/builds/4964031/source?filename=pyqode%2Fcore%2Fapi%2Fcode_edit.py#L853) by those [two tests](https://github.com/pyQode/pyqode.core/blob/master/test/test_api/test_code_edit.py#L355))

**Comment by ewerybody** [comment]
This deleteChar() if in .strip()-empty line thing might have a tiny hole: If there is any whitespace to delete by deleteChar() the lineCount wouldn't change. But OK this is all non-crucial stuff :]

**Big** big thanks for merging in! My first ever official open source contribution!!!

**Comment by ColinDuquesnoy** [comment]
> This deleteChar() if in .strip()-empty line thing might have a tiny hole: If there is any whitespace to delete by deleteChar() the lineCount wouldn't change. But OK this is all non-crucial stuff :]

Good catch! I've fixed it.

> Big big thanks for merging in! My first ever official open source contribution!!!

You're very welcome!

**Pull request merged**
